image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - snakemake.snakemake-lang
    - ms-toolsai.jupyter
    - sndst00m.vscode-native-svg-preview
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
