image:
    file: .gitpod.Dockerfile
tasks:
  - name: main terminal
    command: |
      conda init
      conda activate nextstrain
      conda install nextstrain-cli \
       -c conda-forge -c bioconda \
       --strict-channel-priority \
       --override-channels
      nextstrain setup conda
      nextstrain setup --set-default conda


vscode:
  extensions:
    - snakemake.snakemake-lang
    - ms-toolsai.jupyter
    - sndst00m.vscode-native-svg-preview
